FROM python:3.9

RUN pip3 install redis==4.1.4 \
    	 	 hotqueue==0.2.8 \
		 matplotlib==3.3.4 \
		 Flask==2.0.3 \
		 numpy==1.20.3

WORKDIR /app/
COPY ./src/* /app/
ENTRYPOINT ["python3"]
CMD ["worker-copy.py"]
