---
apiVersion: v1
kind: Service
metadata:
  name: abdon01-prod-service
  labels:
    username: abdon01
    env: prod
spec:
  type: ClusterIP
  selector:
    app: abdon01-prod-db
  ports:
  - name: abdon01-prod
    port: 6379
    targetPort: 6379
