---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asteroid-flask-deployment
  labels:
    app: asteroid-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asteroid-flask
  template:
    metadata:
      labels:
        app: asteroid-flask
    spec:
      containers:
        - name: asteroid-flask
          imagePullPolicy: Always
          image: costaki33/asteroid-data-wrk:0.1
          env:
          - name: REDIS_IP
            value: "10.110.87.96"
          ports:
          - name: http
            containerPort: 5000
