---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asteroid-wrk-deployment
  labels:
    app: asteroid-data-wrk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asteroid-data-wrk
  template:
    metadata:
      labels:
        app: asteroid-data-wrk
    spec:
      containers:
        - name: asteroid-data-wrk
          imagePullPolicy: Always
          image: costaki33/asteroid-data-wrk:0.1
          env:
          - name: REDIS_IP
            value: "10.109.228.201"
