---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abdon01-prod-api-dep
  labels:
    username: abdon01
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abdon01-prod-api
  template:
    metadata:
      labels:
        username: abdon01
        env: prod
        app: abdon01-prod-api
   spec:
      containers:
        - name: apidep
          imagePullPolicy: Always
          image: abdon01/asteroid_api:final
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
