---
apiVersion: v1
kind: Service
metadata:
  name: asteroid-flask-service
spec:
  type: ClusterIP
  selector:
    app: asteroid-flask
  ports:
  - name: asteroid-flask
    port: 5000
    targetPort: 5000
