---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abdon01-prod-deployment
  labels:
    username: abdon01
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abdon01-prod-db
  template:
    metadata:
      labels:
        username: abdon01
        env: prod
        app: abdon01-prod-db
    spec:
      containers:
        - name: dbdep
          image: redis:6
          volumeMounts:
          - name: abdon01-prod-pvc
            mountPath: "/data"
      volumes:
      - name: abdon01-prod-pvc
        persistentVolumeClaim:
          claimName: abdon01-prod-pvc
