---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asteroid-db-deployment
  labels:
    app: asteroid-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asteroid-db
  template:
    metadata:
      labels:
        app: asteroid-db
    spec:
      containers:
        - name: earthquake-db
          image: redis:6
          ports:
          - name: asteroid
            containerPort: 6379   
          volumeMounts:  
            - name: data
              mountPath: "/data"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
