---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abdon01-prod-wrk-dep
  labels:
    username: abdon01
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abdon01-prod-wrk
  template:
    metadata:
      labels:
        username: abdon01
        env: prod
        app: abdon01-prod-wrk
    spec:
      containers:
        - name: wrkdep
          imagePullPolicy: Always
          image: costaki33/asteroid-data-wrk:0.1
          env:
          - name: WORKER_APP
            value: "worker.py"
          - name: REDIS_IP
            value: "10.108.245.241"