---
apiVersion: v1
kind: Service
metadata:
  name: abdon01-prod-service-api
  labels:
    username: abdon01
    env: prod
spec:
  type: ClusterIP
  selector:
    app: abdon01-prod-api
  ports:
  - name: abdon01-prod-api
    port: 5000
    targetPort: 5000

