---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abdon01-test-pvc
  labels:
    username: abdon01
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi