---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abdon01-prod-wrk-dep
  labels:
    username: abdon01
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abdon01-prod-wrk
  template:
    metadata:
      labels:
        username: abdon01
        env: prod
        app: abdon01-prod-wrk
   spec:
      containers:
        - name: apidep
          imagePullPolicy: Always
          image: costaki33/asteroid-data-wrk:0.1
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000

