---
apiVersion: v1
kind: Service
metadata:
  name: abdon01-test-service
  labels:
    username: abdon01
    env: test
spec:
  type: ClusterIP
  selector:
    app: abdon01-test-redis
  ports:
  - name: abdon01-test
    port: 6379
    targetPort: 6379